### ISSUE TITLE
Large Individual fundraiser widget padding/title size

### ISSUE THREAD

**Issue by klmatthews4** [Lovely-Development-Team/St-Jude-Widget-App#124]
![image](https://user-images.githubusercontent.com/90142334/187464887-79a49ed4-c5e0-4961-896c-bf40e9eaa791.png) The full event widget is fine, but large individual fundraiser widget has a larger title and the content looks like it's falling off the bottom of the widget

**Comment by klmatthews4** [comment]
I'm honestly not sure why this spacing doesn't match the overall campaign one but I guess you'd need to look at the code to figure that out

**Comment by benbacardi** [comment]
iOS's behaviour that we can't change I'm afraid.
