### ISSUE TITLE
Fix Siri Support (ITMS-90626)

### ISSUE THREAD

**Issue by RosemaryOrchard** [Lovely-Development-Team/St-Jude-Widget-App#20]
ITMS-90626: Invalid Siri Support - Localized description for custom intent: 'Configuration' not found for locale: en

**Comment by tonyskyday** [comment]
<img width="801" alt="Screen Shot 2021-09-04 at 10 14 47 PM" src="https://user-images.githubusercontent.com/3431655/132112687-47763de4-1fcd-404e-bdb1-774915f96f0b.png">
I think this looks like the offending missing description.
